# Generated by Django 4.1.7 on 2023-03-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatsu_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
